// GENERATED by apps/web/scripts/sync-product-images.mjs — do not edit by hand.
// Regenerate with:  npm run images:sync -w @inkhaus/web
//
// Every entry is a file committed under apps/web/public/products/<slug>/.
// An empty map is a valid state: the storefront falls back to the SVG blanks.
import type { ProductImage } from "./catalog";

export const PRODUCT_IMAGES: Record<string, ProductImage[]> = {};
